name: Daily News Fetch

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8am UTC
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run news fetch script
        run: python news_fetch.py

      - name: Commit updated HTML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.html
          git commit -m "📰 Update news dashboard" || echo "No changes to commit"
          git push
